### ISSUE TITLE
Loading config.yaml gets in issue

### ISSUE THREAD

**Issue by mmkolbe** [Simple-Robotics/cosypose#23]
When I try to run run_cosypose_eval, I get stuck in this last line 'Renderer = NVIDIA GeForce RTX 3060/PCIe/SSE2':

> cosypose) marcel@marcel-Aspire-GX-783:~/cosypose$ python -m cosypose.scripts.run_cosypose_eval --config tless-siso
> Setting OMP and MKL num threads to 1.
> pybullet build time: Nov 28 2023 23:50:19
> 0:00:00.000706 - Starting ...
> 0:00:03.711255 - SAVE DIR: /home/marcel/cosypose/local_data/results/tless-siso-n_views=1--9590382802
> 0:00:03.711346 - Coarse: tless-coarse--10219
> 0:00:03.711405 - Refiner: tless-refiner--585928
> 0:00:04.024363 - Building index and loading annotations...
> [Memory]4.7s, 0.1min    : Loading build_index...
> Traceback (most recent call last):
>   File "/home/marcel/anaconda3/envs/cosypose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/marcel/anaconda3/envs/cosypose/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/marcel/cosypose/cosypose/scripts/run_cosypose_eval.py", line 491, in <module>
>     main()
>   File "/home/marcel/cosypose/cosypose/scripts/run_cosypose_eval.py", line 341, in main
>     predictor, mesh_db = load_models(coarse_run_id, refiner_run_id, n_workers=n_plotters, object_set=object_set)
>   File "/home/marcel/cosypose/cosypose/scripts/run_cosypose_eval.py", line 250, in load_models
>     coarse_model = load_model(coarse_run_id)
>   File "/home/marcel/cosypose/cosypose/scripts/run_cosypose_eval.py", line 236, in load_model
>     cfg = yaml.load((run_dir / 'config.yaml').read_text(), Loader=yaml.FullLoader)
>   File "/home/marcel/anaconda3/envs/cosypose/lib/python3.7/site-packages/yaml/__init__.py", line 81, in load
>     return loader.get_single_data()
>   File "/home/marcel/anaconda3/envs/cosypose/lib/python3.7/site-packages/yaml/constructor.py", line 51, in get_single_data
>     return self.construct_document(node)
>   File "/home/marcel/anaconda3/envs/cosypose/lib/python3.7/site-packages/yaml/constructor.py", line 55, in construct_document
>     data = self.construct_object(node)
>   File "/home/marcel/anaconda3/envs/cosypose/lib/python3.7/site-packages/yaml/constructor.py", line 100, in construct_object
>     data = constructor(self, node)
>   File "/home/marcel/anaconda3/envs/cosypose/lib/python3.7/site-packages/yaml/constructor.py", line 429, in construct_undefined
>     node.start_mark)
> yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object:argparse.Namespace'
>   in "<unicode string>", line 1, column 1:
>     !!python/object:argparse.Namespace
>     ^
> EGL device choice: 0 of 4 (from EGL_VISIBLE_DEVICES)
> EGL device choice: 0 of 4 (from EGL_VISIBLE_DEVICES)
> EGL device choice: 0 of 4 (from EGL_VISIBLE_DEVICES)
> Loaded EGL 1.5 after reload.
> Loaded EGL 1.5 after reload.
> Loaded EGL 1.5 after reload.
> EGL device choice: 0 of 4 (from EGL_VISIBLE_DEVICES)
> EGL device choice: 0 of 4 (from EGL_VISIBLE_DEVICES)
> Loaded EGL 1.5 after reload.
> Loaded EGL 1.5 after reload.
> EGL device choice: 0 of 4 (from EGL_VISIBLE_DEVICES)
> EGL device choice: 0 of 4 (from EGL_VISIBLE_DEVICES)
> Loaded EGL 1.5 after reload.
> EGL device choice: 0 of 4 (from EGL_VISIBLE_DEVICES)
> Loaded EGL 1.5 after reload.
> GL_VENDOR=NVIDIA Corporation
> GL_RENDERER=NVIDIA GeForce RTX 3060/PCIe/SSE2
> GL_VERSION=3.3.0 NVIDIA 560.35.03
> GL_SHADING_LANGUAGE_VERSION=3.30 NVIDIA via Cg compiler
> Version = 3.3.0 NVIDIA 560.35.03
> Vendor = NVIDIA Corporation
> Renderer = NVIDIA GeForce RTX 3060/PCIe/SSE2
> Loaded EGL 1.5 after reload.
> GL_VENDOR=NVIDIA Corporation
> GL_RENDERER=NVIDIA GeForce RTX 3060/PCIe/SSE2
> GL_VERSION=3.3.0 NVIDIA 560.35.03
> GL_SHADING_LANGUAGE_VERSION=3.30 NVIDIA via Cg compiler
> Version = 3.3.0 NVIDIA 560.35.03
> Vendor = NVIDIA Corporation
> Renderer = NVIDIA GeForce RTX 3060/PCIe/SSE2
> GL_VENDOR=NVIDIA Corporation
> GL_RENDERER=NVIDIA GeForce RTX 3060/PCIe/SSE2
> GL_VERSION=3.3.0 NVIDIA 560.35.03
> GL_SHADING_LANGUAGE_VERSION=3.30 NVIDIA via Cg compiler
> Version = 3.3.0 NVIDIA 560.35.03
> Vendor = NVIDIA Corporation
> Renderer = NVIDIA GeForce RTX 3060/PCIe/SSE2
> GL_VENDOR=NVIDIA Corporation
> GL_RENDERER=NVIDIA GeForce RTX 3060/PCIe/SSE2
> GL_VERSION=3.3.0 NVIDIA 560.35.03
> GL_SHADING_LANGUAGE_VERSION=3.30 NVIDIA via Cg compiler
> Version = 3.3.0 NVIDIA 560.35.03
> Vendor = NVIDIA Corporation
> Renderer = NVIDIA GeForce RTX 3060/PCIe/SSE2
> GL_VENDOR=NVIDIA Corporation
> GL_RENDERER=NVIDIA GeForce RTX 3060/PCIe/SSE2
> GL_VERSION=3.3.0 NVIDIA 560.35.03
> GL_SHADING_LANGUAGE_VERSION=3.30 NVIDIA via Cg compiler
> Version = 3.3.0 NVIDIA 560.35.03
> Vendor = NVIDIA Corporation
> Renderer = NVIDIA GeForce RTX 3060/PCIe/SSE2
> GL_VENDOR=NVIDIA Corporation
> GL_RENDERER=NVIDIA GeForce RTX 3060/PCIe/SSE2
> GL_VERSION=3.3.0 NVIDIA 560.35.03
> GL_SHADING_LANGUAGE_VERSION=3.30 NVIDIA via Cg compiler
> Version = 3.3.0 NVIDIA 560.35.03
> Vendor = NVIDIA Corporation
> Renderer = NVIDIA GeForce RTX 3060/PCIe/SSE2
> GL_VENDOR=NVIDIA Corporation
> GL_RENDERER=NVIDIA GeForce RTX 3060/PCIe/SSE2
> GL_VERSION=3.3.0 NVIDIA 560.35.03
> GL_SHADING_LANGUAGE_VERSION=3.30 NVIDIA via Cg compiler
> Version = 3.3.0 NVIDIA 560.35.03
> Vendor = NVIDIA Corporation
> Renderer = NVIDIA GeForce RTX 3060/PCIe/SSE2
> GL_VENDOR=NVIDIA Corporation
> GL_RENDERER=NVIDIA GeForce RTX 3060/PCIe/SSE2
> GL_VERSION=3.3.0 NVIDIA 560.35.03
> GL_SHADING_LANGUAGE_VERSION=3.30 NVIDIA via Cg compiler
> Version = 3.3.0 NVIDIA 560.35.03
> Vendor = NVIDIA Corporation
> Renderer = NVIDIA GeForce RTX 3060/PCIe/SSE2

**Comment by mmkolbe** [comment]
It worked:

In the file cosypose/scripts/run_cosypose_eval.py, I replaced this:
`fg = yaml.load((run_dir / 'config.yaml').read_text(), Loader=yaml.FullLoader)`
By this:

`cfg = yaml.unsafe_load((run_dir / 'config.yaml').read_text())`
